auction/apps/auction_web/lib/auction_web/router.ex
defmodule AuctionWeb.Router do
  use AuctionWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end

  scope "/", AuctionWeb do
    pipe_through :browser # Use the default browser stack

    get "/", AuctionController, :index

    resources "/auctions", AuctionController do
      resources "items", AuctionItemController, only: [:show]
    end

    resources "/users", UserController
  end

  scope "/auth", AuctionWeb do
    pipe_through :browser

    get "/logout", AuthenticationController, :delete, as: :auth
    get "/:provider", AuthenticationController, :request, as: :auth
    get "/:provider/callback", AuthenticationController, :callback, as: :auth
    post "/:provider/callback", AuthenticationController, :callback, as: :auth
  end

  scope "/graphql" do
    pipe_through [:api]

    forward "/", Absinthe.Plug, schema: AuctionWeb.Schema
  end

  scope "/graphiql" do
    pipe_through [:api]

    forward "/", Absinthe.Plug.GraphiQL, schema: AuctionWeb.Schema
  end

  # Other scopes may use custom stacks.
  # scope "/api", AuctionWeb do
  #   pipe_through :api
  # end
end

auction/apps/auction_web/lib/auction_web/views/layout_view.ex
defmodule AuctionWeb.LayoutView do
  use AuctionWeb, :view

  def page_title(assigns) do
    assigns[:page_title] || "拍品信息"
  end
end

auction/apps/auction_web/lib/auction_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>老钱庄</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <div>
    <header class="header">
      <img class="brand" src="/images/logo.png">
    </header>
    <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
    <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

    <main class="container">
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer class="footer clear">
      <a class="home active" href="<%= auction_path(@conn, :index)%>">
        <span>拍卖专场</span>
      </a>
      <a class="order" href="">
        <span>订单</span>
      </a>
      <a class="user" href="">
        <span>用户</span>
      </a>
    </footer>
  </div>
</body>

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</html>

auction/apps/auction_web/lib/auction_web/templates/layout/app_org.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Auction!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
        <nav role="navigation">
          <ul class="nav nav-pills pull-right">
            <li><a href="http://www.phoenixframework.org/docs">Get Started</a></li>
          </ul>
        </nav>
        <span class="logo"></span>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

auction/apps/auction_web/lib/auction_web/templates/layout/auction.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title>老钱庄</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Auction!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </head>

  <body>
    <div class="wrap">
        <div class="top">
          <a class="back" href=""></a>
          <input type="text" placeholder="请输入速拍专场代号快捷进入" />
	      </div>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main wrap">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <!--  -->
<div class="quick-foot flex">
	<a class="flex1 active" href="">
		<span>快速切换</span>
	</a>
	<a class="flex1" href="">
		<span>下一拍品</span>
	</a>
	<a class="flex1" href="">
		<span>更多拍品</span>
	</a>
</div>
  </body>
</html>

auction/apps/auction_web/lib/auction_web/templates/layout/go_back.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
  <title>老钱庄</title>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
</head>
<body>
  <header style="padding:15px 7px; font-size: 18px">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true" onclick="App.goBack()"></span>
    <span style="margin-left: 7px"><%= page_title(assigns)%></span>
  </header>
  <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
  <p class="alert alert-danger" role="alert"><%= get_flash(@conn,:error) %></p>

  <main>
    <%= render @view_module, @view_template, assigns %>
  </main>
</body>

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
<script src="https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</html>